name: Fuel Price Scraper

on:
  workflow_dispatch:

  schedule:
    # every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas beautifulsoup4 playwright gspread google-auth
          playwright install chromium

      - name: Run fuel price scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python fuelprice_to_gsheets.py
